In [2]:
import streamlit as st
import plotly.graph_objects as go
from utils import load_data
df = load_data()
df.head()

2026-04-10 21:10:47.170 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-04-10 21:10:47.178 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-04-10 21:10:47.178 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

         brand          model       engine  ...       fuel_type  seats  torque
0      ferrari  sf90 stradale           v8  ...  hybrid in plug      2   800.0
1  rolls royce        phantom          v12  ...          petrol      5   900.0
2         ford            ka+  1.2l petrol  ...          petrol      5   100.0
3     mercedes        gt 63 s           v8  ...          petrol      4   900.0
4         audi     audi r8 gt          v10  ...          petrol      2   560.0

[5 rows x 11 columns]

In [3]:
auto_seleccionado1 = "sf90 stradale"
filtrar_auto_seleccionado1 = df[df["model"] == auto_seleccionado1]
filtrar_auto_seleccionado1

     brand          model engine  ...       fuel_type  seats  torque
0  ferrari  sf90 stradale     v8  ...  hybrid in plug      2   800.0

[1 rows x 11 columns]

In [4]:
filtrar_auto_seleccionado1["engine"][0]

'v8'

In [5]:
for col in df.select_dtypes(include="object").columns:
    print(col)
    print(df[col].nunique())

brand
31
model
1189
engine
347
fuel_type
14

In [6]:
df.groupby("brand")["price"].mean().sort_values(ascending=False).index

Index(['bugatti', 'aston martin', 'lamborghini', 'ferrari', 'rolls royce',
       'bentley', 'porsche', 'volvo', 'tesla', 'mercedes', 'audi', 'mazda',
       'jaguar land rover', 'bmw', 'gmc', 'acura', 'cadillac', 'nissan',
       'jeep', 'ford', 'chevrolet', 'toyota', 'volkswagen', 'kia', 'peugeot',
       'hyundai', 'honda', 'mitsubishi', 'mahindra', 'tata motors',
       'maruti suzuki'],
      dtype='object', name='brand')

In [7]:
df[df["price"] == 18000000]

       brand             model               engine  ...  fuel_type  seats  torque
884  bugatti  la voiture noire  8.0l quad-turbo w16  ...     petrol      2  1600.0

[1 rows x 11 columns]

In [8]:
sorted(df["fuel_type"].unique())

['awd petrol',
 'cng petrol',
 'diesel',
 'diesel petrol',
 'electric',
 'electric gas hybrid',
 'electric hybrid',
 'ev petrol',
 'gas hybrid',
 'hybrid',
 'hybrid in plug',
 'hybrid petrol',
 'hydrogen',
 'petrol']